# Generated by Django 4.1.3 on 2022-11-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0003_rename_about_video_video_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='caption',
            new_name='text',
        ),
    ]
